local Heros = { 
['ace'] =  { 
['ability_01'] = {
	['name'] = "Ability_Ace1",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['manacost'] = { [1] = 65,[2] = 70,[3] = 75,[4] = 80, },
	['cooldowntime'] = "6000",
	['actiontype'] = "target_self",
	['targetradius'] = "350",
	['queue'] = "front",
	['inheritmovement'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Ace2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetradius'] = "300",
	['targetscheme'] = "enemy_units",
	['activatescheme'] = "movement",
	['manacost'] = "100",
	['cooldowntime'] = { [1] = 18000,[2] = 16000,[3] = 14000,[4] = 12000, },
	['novoiceresponse'] = "true",
	['queue'] = "dropmovement",
	['range'] = "600",
	['showareacast'] = "true",
	['hoverareacastrange'] = "600",
	['allowoutofrangecast'] = "true",
	['disabled'] = "true",
}, 

['ability_03'] = {
	['name'] = "Ability_Ace3",
	['icon'] = "icon.tga",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['anim'] = "ability_3",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['manacost'] = "50",
	['cooldowntime'] = "12000",
	['queue'] = "front",
	['inheritmovement'] = "true",
	['alwaysshowtimer'] = "true",
}, 

['ability_04'] = {
	['name'] = "Ability_Ace4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "800",
	['castactiontime'] = "300",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 100,[2] = 115,[3] = 130, },
	['cooldowntime'] = "60000",
	['novoiceresponse'] = "true",
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
	['range'] = "200",
	['showareacast'] = "true",
	['hoverareacastrange'] = "200",
	['radius'] = "600",
	['targetselection'] = "closest",
	['targetscheme'] = "visible_enemy_heroes",
	['maxtotalimpacts'] = "1",
	['disabled'] = "true",
}, 
['bastion'] =  { 
['ability_01'] = {
	['name'] = "Ability_Bastion1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "250",
	['castactiontime'] = "150",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "all_units",
	['showconecast'] = "true",
	['conecastwidth'] = "450",
	['conecastrange'] = "600",
	['allowoutofrangecast'] = "true",
	['manacost'] = { [1] = 70,[2] = 80,[3] = 90,[4] = 100, },
	['cooldowntime'] = "9000",
	['range'] = "550",
	['novoiceresponse'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Bastion2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2_up",
	['casttime'] = "450",
	['castactiontime'] = "450",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "target_position",
	['activatescheme'] = "movement",
	['manacost'] = "90",
	['range'] = "760",
	['cooldowntime'] = "16000",
	['noturntotarget'] = "false",
	['novoiceresponse'] = "true",
	['showlinecast'] = "true",
	['linecastrange'] = "-1",
	['linecastmaxrange'] = "900",
	['linecastwidth'] = "140",
	['queue'] = "dropmovement",
	['showareacast'] = "true",
	['allowoutofrangecast'] = "true",
	['usepathforrange'] = "true",
}, 

['ability_03'] = {
	['name'] = "Ability_Bastion3",
	['icon'] = "icon.tga",
	['anim'] = "ability_3",
	['casttime'] = "200",
	['castactiontime'] = "200",
	['showareacast'] = "true",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['targetscheme'] = "enemy_units",
	['queue'] = "front",
	['manacost'] = { [1] = 50,[2] = 55,[3] = 60,[4] = 65, },
	['cooldowntime'] = "25000",
	['maxhealth'] = { [1] = 40,[2] = 80,[3] = 120,[4] = 160, },
	['range'] = "600",
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
	['radius'] = "600",
	['targetselection'] = "all",
	['targetscheme'] = "ally_units",
}, 

['ability_04'] = {
	['name'] = "Ability_Bastion4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['queue'] = "front",
	['inheritmovement'] = "true",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_self",
	['targetscheme'] = "self",
	['manacost'] = { [1] = 110,[2] = 125,[3] = 140, },
	['cooldowntime'] = "120000",
	['hoverareacastrange'] = "400",
	['novoiceresponse'] = "true",
	['disabled'] = "true",
}, 
['blazer'] =  { 
['ability_01'] = {
	['name'] = "Ability_Blazer1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['inheritmovement'] = "true",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['activateimpacttime'] = "4000",
	['allowoutofrangecast'] = "true",
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 95,[2] = 100,[3] = 105,[4] = 110, },
	['cooldowntime'] = "13000",
	['noquickcast'] = "true",
	['alwaysshowtimer'] = "true",
	['noninterrupting'] = "true",
	['ignorecooldown'] = "true",
	['anim'] = "ability_1_fire",
	['icon'] = "icon2.tga",
	['casttime'] = "200",
	['castactiontime'] = "200",
	['manacost'] = "0",
	['cooldowntime'] = "0",
	['activateimpacttime'] = "0",
	['range'] = "1065",
	['forcerange'] = "1065",
	['allowoutofboundscast'] = "true" ,
	['allowoutofrangecast'] = "true",
	['showlinecast'] = "true",
	['linecastrangestart'] = "635",
	['linecastrangemid'] = "1200",
	['linecastrangeend'] = "1200",
	['linecastrangemidpos'] = "0.3",
	['linecastrangeduration'] = "4000",
	['linecastwidth'] = "135",
	['showareacast'] = "true",
	['areacastrangestart'] = "635",
	['areacastrangemid'] = "1200",
	['areacastrangeend'] = "1200",
	['areacastrangemidpos'] = "0.3",
	['areacastrangeduration'] = "4000",
	['hoverareacastrange'] = "1120",
	['noturntotarget'] = "false",
}, 

['ability_02'] = {
	['name'] = "Ability_Blazer2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "300",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['targetradius'] = "325",
	['manacost'] = "95",
	['cooldowntime'] = "12000",
	['range'] = "800",
	['showareacast'] = "true",
	['disabled'] = "true",
}, 

['ability_03'] = {
	['name'] = "Ability_Blazer3",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['maxcharges'] = "30",
	['basedamage'] = { [1] = 3,[2] = 6,[3] = 9,[4] = 12, },
	['actiontype'] = "passive",
}, 

['ability_04'] = {
	['name'] = "Ability_Blazer4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['cooldowntime'] = { [1] = 60000,[2] = 45000,[3] = 30000, },
	['inheritmovement'] = "true",
	['frontqueue'] = "true",
	['actiontype'] = "target_self",
	['alwaysshowtimer'] = "true",
	['manacost'] = "100",
	['disabled'] = "true",
}, 
['bo'] =  { 
['ability_01'] = {
	['name'] = "Ability_Bo1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "300",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 85,[2] = 90,[3] = 95,[4] = 100, },
	['cooldowntime'] = "9000",
	['novoiceresponse'] = "true",
	['range'] = "865",
	['forcerange'] = "865",
	['showlinecast'] = "true",
	['linecastrange'] = "1000",
	['linecastwidth'] = "135",
	['allowoutofrangecast'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Bo2",
	['icon'] = "icon.tga",
	['anim'] = "",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['manacost'] = { [1] = 85,[2] = 90,[3] = 95,[4] = 100, },
	['queue'] = "front",
	['inheritmovement'] = "true",
	['cooldowntime'] = "15000",
	['hoverareacastrange'] = "300",
	['alwaysshowtimer'] = "true",
	['ignorecooldown'] = "true",
	['anim'] = "",
	['icon'] = "charging.tga",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['manacost'] = "0",
	['actiontype'] = "no_target",
	['cooldowntime'] = "0",
}, 

['ability_03'] = {
	['name'] = "Ability_Bo3",
	['icon'] = "icon.tga",
	['anim'] = "ability_3",
	['casttime'] = "200",
	['castactiontime'] = "200",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['targetradius'] = "550",
	['manacost'] = { [1] = 70,[2] = 75,[3] = 80,[4] = 85, },
	['cooldowntime'] = { [1] = 50000,[2] = 40000,[3] = 32000,[4] = 25000, },
	['range'] = "550",
	['queue'] = "front",
	['noentercombat'] = "true",
	['showareacast'] = "true" ,
}, 

['ability_04'] = {
	['name'] = "Ability_Bo4",
	['icon'] = "icon.tga"	,
	['anim'] = "ability_4",
	['casttime'] = "300",
	['castactiontime'] = "300",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_position",
	['activatescheme'] = "movement",
	['targetradius'] = "170",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 110,[2] = 125,[3] = 140, },
	['cooldowntime'] = { [1] = 90000,[2] = 75000,[3] = 60000, },
	['queue'] = "dropmovement",
	['range'] = "900",
	['forcerange'] = "900",
	['allowoutofboundscast'] = "true",
	['allowoutofrangecast'] = "true",
	['showlinecast'] = "true",
	['linecastwidth'] = "200",
	['linecastrange'] = "985",
}, 
['caprice'] =  { 
['ability_01'] = {
	['name'] = "Ability_Caprice1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "350",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['manacost'] = { [1] = 70,[2] = 80,[3] = 90,[4] = 100, },
	['cooldowntime'] = "9000",
	['range'] = "700",
	['forcerange'] = "700",
	['allowoutofrangecast'] = "true",
	['showlinecast'] = "true",
	['linecastwidth'] = "180",
	['linecastrange'] = "880",
	['showareacast'] = "true",
	['areacastrange'] = "880",
}, 

['ability_02'] = {
	['name'] = "Ability_Caprice2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "150",
	['castactiontime'] = "150",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetradius'] = "215",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 70,[2] = 80,[3] = 90,[4] = 100, },
	['cooldowntime'] = "11000",
	['range'] = "550",
	['showareacast'] = "true",
}, 

['ability_03'] = {
	['name'] = "Ability_Caprice3",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['modifierkey'] = "Caprice_Ability3_Learned",
	['actiontype'] = "passive",
}, 

['ability_04'] = {
	['name'] = "Ability_Caprice4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "150",
	['castactiontime'] = "150",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_position",
	['targetradius'] = "600",
	['targetscheme'] = "enemy_units",
	['activatescheme'] = "movement",
	['manacost'] = { [1] = 70,[2] = 80,[3] = 90, },
	['range'] = "600",
	['cooldowntime'] = "0",
	['noturntotarget'] = "false",
	['novoiceresponse'] = "true",
	['allowoutofrangecast'] = "true",
	['nonreseting'] = "true",
	['noninterupting'] = "true",
	['alwaysshowtimer'] = "true",
	['queue'] = "dropmovement",
	['maxcharges'] = "2",
	['showareacast'] = "true",
	['disabled'] = "true",
}, 
['carter'] =  { 
['ability_01'] = {
	['name'] = "Ability_Carter1",
	['icon'] = "icon.tga",
	['anim'] = "",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetradius'] = "70",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 50,[2] = 55,[3] = 60,[4] = 65, },
	['cooldowntime'] = "0",
	['queue'] = "front",
	['inheritmovement'] = "true",
	['noturntotarget'] = "false",
	['range'] = "2500",
	['forcerange'] = "2500",
	['allowoutofrangecast'] = "true",
	['allowoutofboundscast'] = "true",
	['showlinecast'] = "true",
	['linecastwidth'] = "90",
	['linecastrange'] = "2600",
	['maxcharges'] = "2",
	['showareacast'] = "false",
	['alwaysshowtimer'] = "true",
	['doubleactivate'] = "false",
	['doubleactivatenoninterrupting'] = "true",
	['radius'] = "600",
	['targetselection'] = "closest",
	['targetscheme'] = "visible_enemy_heroes",
	['maxtotalimpacts'] = "1",
	['disabled'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Carter2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "750",
	['castactiontime'] = "0",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetradius'] = "250",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 70,[2] = 80,[3] = 90,[4] = 100, },
	['cooldowntime'] = "10000",
	['range'] = "850",
	['showareacast'] = "true",
	['hoverareacastrange'] = "850",
}, 

['ability_03'] = {
	['name'] = "Ability_Carter3",
	['icon'] = "icon.tga",
	['anim'] = "ability_3",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "no_target",
	['hoverareacastrange'] = "325",
	['targetscheme'] = "enemy_units",
	['queue'] = "front",
	['inheritmovement'] = "true",
	['manacost'] = "40",
	['cooldowntime'] = "5000",
	['modifierkey'] = { [1] = carter3_1,[2] = carter3_2,[3] = carter3_3,[4] = carter3_4, },
}, 

['ability_04'] = {
	['name'] = "Ability_Carter4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "500",
	['castactiontime'] = "0",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "enemy_heroes",
	['range'] = "1200",
	['manacost'] = { [1] = 100,[2] = 115,[3] = 130, },
	['cooldowntime'] = "75000",
	['showareacast'] = "true",
	['alwaysshowtimer'] = "true",
}, 
['chester'] =  { 
['ability_01'] = {
	['name'] = "Ability_Chester1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1" ,
	['casttime'] = "400",
	['castactiontime'] = "200",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 70,[2] = 75,[3] = 80,[4] = 85, },
	['cooldowntime'] = { [1] = 10000,[2] = 8000,[3] = 6000,[4] = 4000, },
	['range'] = "1145",
	['forcerange'] = "1145",
	['allowoutofrangecast'] = "true",
	['showlinecast'] = "true",
	['linecastrange'] = "1200",
	['linecastwidth'] = "110",
}, 

['ability_02'] = {
	['name'] = "Ability_Chester2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "250",
	['castactiontime'] = "250",
	['queue'] = "front",
	['inheritmovement'] = "true",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "ally_heroes",
	['manacost'] = "95",
	['cooldowntime'] = { [1] = 23000,[2] = 20000,[3] = 17000,[4] = 14000, },
	['range'] = "700",
	['noentercombat'] = "true",
	['showareacast'] = "true" ,
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
}, 

['ability_03'] = {
	['name'] = "Ability_Chester3",
	['icon'] = "icon.tga",
	['anim'] = "ability_3",
	['casttime'] = "300",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['manacost'] = { [1] = 85,[2] = 90,[3] = 95,[4] = 100, },
	['cooldowntime'] = "12000",
	['actiontype'] = "target_entity",
	['targetscheme'] = "enemy_heroes",
	['range'] = "600",
	['showareacast'] = "true" ,
	['target'] = "target_entity" ,
	['owner'] = "source_entity",
	['source'] = "target_entity",
	['count'] = "1" ,
	['lifetime'] = "10000" ,
	['receivedamagemultiplier'] = "2" ,
	['inflictdamagemultiplier'] = { [1] = 0.2,[2] = 0.25,[3] = 0.3,[4] = 0.35, },
	['pushentity'] = "true",
	['uncontrollable'] = "true",
	['fixedposition'] = "true",
}, 

['ability_04'] = {
	['name'] = "Ability_Chester4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "300",
	['castactiontime'] = "300",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "other_ally_heroes",
	['manacost'] = { [1] = 100,[2] = 110,[3] = 120, },
	['cooldowntime'] = "75000",
	['showareacast'] = "true",
	['hoverareacastrange'] = "900",
	['range'] = "900",
}, 
['claudessa'] =  { 
['ability_01'] = {
	['name'] = "Ability_Claudessa1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "350",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['manacost'] = { [1] = 95,[2] = 100,[3] = 105,[4] = 110, },
	['cooldowntime'] = { [1] = 14000,[2] = 12000,[3] = 10000,[4] = 8000, },
	['range'] = "800",
	['forcerange'] = "800",
	['allowoutofrangecast'] = "true",
	['hoverareacastrange'] = "1060",
	['showconecast'] = "true",
	['conecastwidth'] = "512",
	['conecastrange'] = "1114",
}, 

['ability_02'] = {
	['name'] = "Ability_Claudessa2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "700",
	['castactiontime'] = "200",
	['showareacast'] = "true",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "ally_heroes",
	['manacost'] = { [1] = 80,[2] = 90,[3] = 100,[4] = 110, },
	['cooldowntime'] = "14000",
	['range'] = "600",
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
	['radius'] = "700",
	['targetselection'] = "closest",
	['targetscheme'] = "ally_heroes",
	['maxtotalimpacts'] = "1",
}, 

['ability_03'] = {
	['name'] = "Ability_Claudessa3",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "passive",
	['cooldowntime'] = { [1] = 11000,[2] = 9000,[3] = 7000,[4] = 5000, },
	['showareacast'] = "true",
}, 

['ability_04'] = {
	['name'] = "Ability_Claudessa4",
	['icon'] = "icon.tga",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['anim'] = "ability_4",
	['actiontype'] = "target_self",
	['cooldowntime'] = "135000",
	['queue'] = "front",
	['inheritmovement'] = "true",
	['manacost'] = { [1] = 90,[2] = 105,[3] = 120, },
	['hoverareacastrange'] = "350",
	['alwaysshowtimer'] = "true",
	['showareacast'] = "true",
}, 
['fetterstone'] =  { 
['ability_01'] = {
	['name'] = "Ability_Fetterstone1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "200",
	['castactiontime'] = "150",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 45,[2] = 50,[3] = 55,[4] = 60, },
	['cooldowntime'] = "2000",
	['range'] = "800",
	['forcerange'] = "800",
	['allowoutofboundscast'] = "true" ,
	['allowoutofrangecast'] = "true",
	['showlinecast'] = "true",
	['linecastwidth'] = "90",
	['linecastrange'] = "870",
	['hoverareacastrange'] = "890",
	['doubleactivatenoninterrupting'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Fetterstone2",
	['icon'] = "icon.tga",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['frontqueue'] = "true",
	['inheritmovement'] = "true",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['manacost'] = "90",
	['cooldowntime'] = "16000",
	['hoverareacastrange'] = "800",
}, 

['ability_03'] = {
	['name'] = "Ability_Fetterstone3",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "passive",
	['powerpercharge'] = "1",
	['maxcharges'] = "100",
	['power'] = { [1] = 3,[2] = 5,[3] = 7,[4] = 9, },
}, 

['ability_04'] = {
	['name'] = "Ability_Fetterstone4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['cooldowntime'] = "75000",
	['actiontype'] = "target_self",
	['manacost'] = { [1] = 90,[2] = 100,[3] = 110, },
	['queue'] = "front",
	['inheritmovement'] = "true",
	['maxcharges'] = "0",
	['alwaysshowtimer'] = "true",
}, 
['gokong'] =  { 
['ability_01'] = {
	['name'] = "Ability_GoKong1",
	['icon'] = "icon.tga",
	['anim'] = "ablity_1",
	['casttime'] = "150",
	['castactiontime'] = "150",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "self_position",
	['targetscheme'] = "enemy_units",
	['queue'] = "front",
	['targetradius'] = "350",
	['hoverareacastrange'] = "365",
	['manacost'] = "95",
	['cooldowntime'] = { [1] = 13000,[2] = 11000,[3] = 9000,[4] = 7000, },
	['radius'] = "350",
	['targetselection'] = "closest",
	['targetscheme'] = "enemy_heroes",
	['maxtotalimpacts'] = "-1",
	['maximpactspertarget'] = "1",
	['radius'] = "350",
	['targetselection'] = "closest",
	['targetscheme'] = "enemy_nonhero",
	['maxtotalimpacts'] = "-1",
	['maximpactspertarget'] = "1",
}, 

['ability_02'] = {
	['name'] = "Ability_GoKong2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "100",
	['castactiontime'] = "100",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetradius'] = "150",
	['targetscheme'] = "enemy_units",
	['activatescheme'] = "movement",
	['manacost'] = "100",
	['cooldowntime'] = "18000",
	['novoiceresponse'] = "true",
	['queue'] = "dropmovement",
	['range'] = "400",
	['showareacast'] = "true",
	['hoverareacastrange'] = "425",
	['allowoutofrangecast'] = "true",
	['radius'] = "150",
	['targetselection'] = "all",
	['targetscheme'] = "enemy_units",
	['radius'] = "150",
	['targetselection'] = "all",
	['targetscheme'] = "enemy_units",
}, 

['ability_03'] = {
	['name'] = "Ability_GoKong3",
	['icon'] = "icon.tga",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['frontqueue'] = "true",
	['inheritmovement'] = "true",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['manacost'] = "40",
	['cooldowntime'] = "14000",
	['hoverareacastrange'] = "425",
	['alwaysshowtimer'] = "true",
}, 

['ability_04'] = {
	['name'] = "Ability_GoKong4",
	['icon'] = "icon.tga",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['anim'] = "ability_4",
	['actiontype'] = "target_self",
	['ignoreinvulnerable'] = "true",
	['casttime'] = "300",
	['castactiontime'] = "300",
	['inheritmovement'] = "true",
	['range'] = "1500",
	['targetradius'] = "1500",
	['cooldowntime'] = "80000",
	['manacost'] = { [1] = 100,[2] = 110,[3] = 120, },
	['alwaysshowtimer'] = "true",
	['radius'] = "2000",
	['targetselection'] = "all",
	['targetscheme'] = "nonillusion_enemy_heroes",
	['owner'] = "source_entity",
	['source'] = "source_entity",
	['target'] = "target_entity",
	['count'] = "1",
	['lifetime'] = "5000",
	['playdeathanim'] = "false",
	['pushentity'] = "true",
	['uncontrollable'] = "true",
	['nofamiliar'] = "true",
	['anim'] = "",
	['cooldowntime'] = "0",
	['icon'] = "icon_b.tga",
	['actiontype'] = "target_position",
	['targetscheme'] = "my_illusions",
	['allowoutofrangecast'] = "true",
	['range'] = "99999",
	['manacost'] = "0",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['dontshowhovercast'] = "true",
	['ignorecooldown'] = "true",
}, 
['hale'] =  { 
['ability_01'] = {
	['name'] = "Ability_Hale1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "250",
	['castactiontime'] = "250",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['activatescheme'] = "movement",
	['targetradius'] = "200",
	['targetscheme'] = "all_other_units",
	['manacost'] = "95",
	['queue'] = "dropmovement",
	['showconecast'] = "true",
	['conecastwidth'] = "700",
	['conecastrange'] = "1000",
	['cooldowntime'] = { [1] = 18000,[2] = 15000,[3] = 13000,[4] = 11000, },
	['range'] = "475",
	['forcerange'] = "475",
	['novoiceresponse'] = "true",
	['allowoutofrangecast'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Hale2",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['anim'] = "ability_2",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['inheritmovement'] = "true",
	['queue'] = "front",
	['cooldowntime'] = { [1] = 11000,[2] = 9000,[3] = 7000,[4] = 5000, },
	['manacost'] = "70",
	['alwaysshowtimer'] = "true",
}, 

['ability_03'] = {
	['name'] = "Ability_Hale3",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['anim'] = "ability_3",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['inheritmovement'] = "true",
	['queue'] = "front",
	['cooldowntime'] = "16000",
	['manacost'] = { [1] = 55,[2] = 60,[3] = 65,[4] = 70, },
	['alwaysshowtimer'] = "true",
}, 

['ability_04'] = {
	['name'] = "Ability_Hale4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "400",
	['castactiontime'] = "400",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "self_position",
	['targetscheme'] = "enemy_units",
	['targetradius'] = "550",
	['manacost'] = { [1] = 90,[2] = 105,[3] = 120, },
	['cooldowntime'] = "90000",
}, 
['harrower'] =  { 
['ability_01'] = {
	['name'] = "Ability_Harrower1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_cursor",
	['manacost'] = "70",
	['cooldowntime'] = { [1] = 12000,[2] = 10000,[3] = 8000,[4] = 6000, },
	['range'] = "350",
	['forcerange'] = "350",
	['allowoutofrangecast'] = "true",
	['queue'] = "dropmovement",
	['showlinecast'] = "true",
	['linecastwidth'] = "50",
	['linecastrange'] = "350",
	['alwaysshowtimer'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Harrower2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "350",
	['castactiontime'] = "350",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "self_position",
	['targetscheme'] = "visible_enemy_heroes",
	['inheritmovement'] = "true",
	['targetradius'] = "1200",
	['range'] = "1200",
	['queue'] = "front",
	['manacost'] = "105",
	['cooldowntime'] = "15000",
	['radius'] = "1200",
	['targetselection'] = "closest",
	['targetscheme'] = "visible_enemy_heroes",
	['maxtotalimpacts'] = "1",
	['radius'] = "1200",
	['targetselection'] = "closest",
	['targetscheme'] = "visible_enemy_units",
	['maxtotalimpacts'] = "1",
}, 

['ability_03'] = {
	['name'] = "Ability_Harrower3" ,
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "passive",
}, 

['ability_04'] = {
	['name'] = "Ability_Harrower4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_self",
	['queue'] = "front",
	['inheritmovement'] = "true",
	['responsetype'] = "NoResponse BreakStealth",
	['manacost'] = "0",
	['cooldowntime'] = "4000",
	['targetscheme'] = "",
	['noentercombat'] = "true",
}, 
['iah'] =  { 
['ability_01'] = {
	['name'] = "Ability_Iah1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "250",
	['castactiontime'] = "250",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "enemy_units_and_structures",
	['manacost'] = { [1] = 50,[2] = 55,[3] = 60,[4] = 65, },
	['cooldowntime'] = "2000",
	['queue'] = "front",
	['range'] = "700",
	['showareacast'] = "true",
	['allowoutofrangecast'] = "false",
	['allowoutofboundscast'] = "false",
	['maxcharges'] = "2",
	['alwaysshowtimer'] = "true",
	['disabled'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Iah2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "350",
	['castactiontime'] = "350",
	['actiontype'] = "target_position",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['targetradius'] = "300",
	['targetscheme'] = "nonboss_organic_enemy_units",
	['manacost'] = "100",
	['cooldowntime'] = "9000",
	['novoiceresponse'] = "true",
	['range'] = "650",
	['showareacast'] = "true",
	['showrangeandradiusintooltip'] = "true",
}, 

['ability_03'] = {
	['name'] = "Ability_Iah3",
	['icon'] = "icon.tga",
	['anim'] = "ability_3",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['frontqueue'] = "true",
	['inheritmovement'] = "true",
	['targetradius'] = "300",
	['manacost'] = "75",
	['cooldowntime'] = { [1] = 24000,[2] = 20000,[3] = 16000,[4] = 12000, },
}, 

['ability_04'] = {
	['name'] = "Ability_Iah4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "300",
	['castactiontime'] = "300",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_position",
	['manacost'] = { [1] = 100,[2] = 110,[3] = 120, },
	['cooldowntime'] = "75000",
	['targetradius'] = "300",
	['range'] = "999999",
	['hoverareacastrange'] = "1",
}, 
['jinshe'] =  { 
['ability_01'] = {
	['name'] = "Ability_JinShe1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "350",
	['castactiontime'] = "350",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetradius'] = "90",
	['targetscheme'] = "enemy_units",
	['range'] = "750",
	['forcerange'] = "750",
	['allowoutofrangecast'] = "true",
	['allowoutofboundscast'] = "true",
	['queue'] = "front",
	['showlinecast'] = "true",
	['linecastwidth'] = "90",
	['linecastrange'] = "800",
	['manacost'] = { [1] = 85,[2] = 90,[3] = 95,[4] = 100, },
	['cooldowntime'] = "10000" ,
}, 

['ability_02'] = {
	['name'] = "Ability_JinShe2",
	['icon'] = "icon.tga",
	['anim'] = "",
	['casttime'] = "150",
	['castactiontime'] = "150",
	['inheritmovement'] = "true",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "self_position",
	['targetscheme'] = "enemy_units",
	['queue'] = "front",
	['allowoutofrangecast'] = "true",
	['targetradius'] = "375",
	['manacost'] = "70",
	['cooldowntime'] = "8000" ,
	['radius'] = "375",
	['targetselection'] = "all",
	['targetscheme'] = "enemy_units",
	['radius'] = "350",
	['targetselection'] = "all",
	['targetscheme'] = "enemy_units",
}, 

['ability_03'] = {
	['name'] = "Ability_JinShe3",
	['icon'] = "icon.tga",
	['anim'] = "ability_3_channel",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['channeltime'] = "1400",
	['ischanneling'] = "true",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetradius'] = "120",
	['targetscheme'] = "enemy_units",
	['manacost'] = "70",
	['cooldowntime'] = { [1] = 65000,[2] = 45000,[3] = 30000,[4] = 20000, },
	['showareacast'] = "true",
	['range'] = "1800",
	['hoverareacastrange'] = "1800",
	['allowoutofrangecast'] = "true",
}, 

['ability_04'] = {
	['name'] = "Ability_JinShe4",
	['icon'] = "icon.tga",
	['casttime'] = "300",
	['castactiontime'] = "300",
	['anim'] = "ability_4",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['modifierkey'] = "fireballz",
	['actiontype'] = "target_self",
	['cooldowntime'] = "60000",
	['manacost'] = "0",
	['maxcharges'] = "12",
	['radius'] = "9999999",
	['targetselection'] = "all",
	['targetscheme'] = "jinshefire",
	['ignoreinvulnerable'] = "true",
	['radius'] = "9999999",
	['targetselection'] = "all",
	['targetscheme'] = "jinshefire",
	['ignoreinvulnerable'] = "true",
	['maxcharges'] = "0",
}, 
['lady_tinder'] =  { 
['ability_01'] = {
	['name'] = "Ability_Ladytinder1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "400",
	['castactiontime'] = "400",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetradius'] = "70",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 70,[2] = 80,[3] = 90,[4] = 100, },
	['cooldowntime'] = "10000",
	['range'] = "900",
	['forcerange'] = "900",
	['allowoutofrangecast'] = "true",
	['allowoutofboundscast'] = "true",
	['showlinecast'] = "true",
	['linecastwidth'] = "100",
	['linecastrange'] = "1000",
	['showareacast'] = "false",
	['alwaysshowtimer'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Ladytinder2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "800",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "all_units",
	['manacost'] = { [1] = 80,[2] = 90,[3] = 100,[4] = 110, },
	['cooldowntime'] = "8000",
	['range'] = "550",
	['showareacast'] = "true",
	['hoverareacastrange'] = "600",
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
	['disablesmarttarget'] = "true",
	['radius'] = "650",
	['targetselection'] = "closest",
	['targetscheme'] = "ally_heroes",
	['maxtotalimpacts'] = "1",
}, 

['ability_03'] = {
	['name'] = "Ability_Ladytinder3",
	['icon'] = "icon.tga",
	['anim'] = "ability_3",
	['casttime'] = "600",
	['castactiontime'] = "200",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "ally_units",
	['manacost'] = { [1] = 55,[2] = 65,[3] = 75,[4] = 85, },
	['cooldowntime'] = "9000",
	['showareacast'] = "true",
	['hoverareacastrange'] = "700",
	['range'] = "650",
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
	['radius'] = "750",
	['targetselection'] = "closest",
	['targetscheme'] = "ally_heroes",
	['maxtotalimpacts'] = "1",
}, 

['ability_04'] = {
	['name'] = "Ability_Ladytinder4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "1000",
	['castactiontime'] = "300",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_position",
	['targetradius'] = "700",
	['manacost'] = { [1] = 115,[2] = 130,[3] = 145, },
	['cooldowntime'] = "120000",
	['range'] = "600",
	['showareacast'] = "true",
	['hoverareacastrange'] = "590",
}, 
['malady'] =  { 
['ability_01'] = {
	['name'] = "Ability_Malady1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "400",
	['castactiontime'] = "300" ,
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetradius'] = "150",
	['targetscheme'] = "all_other_units",
	['manacost'] = { [1] = 70,[2] = 80,[3] = 90,[4] = 100, },
	['cooldowntime'] = "12000" ,
	['showlinecast'] = "true",
	['linecastwidth'] = "150",
	['linecastrange'] = "865",
	['allowoutofrangecast'] = "true",
	['range'] = "865",
	['forcerange'] = "865",
}, 

['ability_02'] = {
	['name'] = "Ability_Malady2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "200",
	['castactiontime'] = "200",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['showareacast'] = "true",
	['targetradius'] = "230",
	['manacost'] = { [1] = 65,[2] = 75,[3] = 85,[4] = 95, },
	['cooldowntime'] = "12000",
	['range'] = "600",
	['radius'] = "230",
	['targetselection'] = "all",
	['targetscheme'] = "enemy_units",
}, 

['ability_03'] = {
	['name'] = "Ability_Malady3",
	['icon'] = "icon.tga",
	['anim'] = "ability_3",
	['casttime'] = "200",
	['castactiontime'] = "0",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_vector",
	['targetradius'] = "325",
	['targetscheme'] = "enemy_units",
	['manacost'] = "80",
	['cooldowntime'] = { [1] = 30000,[2] = 22000,[3] = 16000,[4] = 12000, },
	['range'] = { [1] = 500,[2] = 650,[3] = 800,[4] = 950, },
	['showareacast'] = "true",
	['hoverareacastrange'] = { [1] = 500,[2] = 650,[3] = 800,[4] = 950, },
	['defaultvectorrotation'] = "90" ,
	['name'] = "Affector_Malady_Ability3",
	['target'] = "target_position",
	['direction'] = "target_position"		,
	['targetorigin'] = "delta_position",
	['directionorigin'] = "delta_position",
	['targetmodifier'] = "pointpastline",
	['directionmodifier'] = "pointpastline",
	['directionvalue'] = "325",
	['targetvalue'] = "-325",
	['firsttarget'] = ""  ,
}, 

['ability_04'] = {
	['name'] = "Ability_Malady4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "850",
	['castactiontime'] = "400",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "enemy_units",
	['showareacast'] = "true",
	['manacost'] = { [1] = 110,[2] = 125,[3] = 140, },
	['cooldowntime'] = "60000",
	['range'] = "600",
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
	['radius'] = "700",
	['targetselection'] = "closest",
	['targetscheme'] = "visible_enemy_heroes",
	['maxtotalimpacts'] = "1",
}, 
['minerva'] =  { 
['ability_01'] = {
	['name'] = "Ability_Minerva1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "200",
	['castactiontime'] = "100",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['activatescheme'] = "movement",
	['actiontype'] = "target_entity",
	['targetscheme'] = "all_other_units",
	['manacost'] = { [1] = 45,[2] = 50,[3] = 55,[4] = 60, },
	['cooldowntime'] = "0",
	['showareacast'] = "true",
	['maxcharges'] = "2",
	['range'] = "400",
	['queue'] = "dropmovement",
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
	['alwaysshowtimer'] = "True",
	['radius'] = "450",
	['targetselection'] = "closest",
	['targetscheme'] = "visible_enemy_heroes",
	['maxtotalimpacts'] = "1",
	['disabled'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Minerva2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "400",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 70,[2] = 80,[3] = 90,[4] = 100, },
	['cooldowntime'] = "10000",
	['range'] = "500",
	['showareacast'] = "true",
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
	['radius'] = "700",
	['targetselection'] = "closest",
	['targetscheme'] = "visible_enemy_heroes",
	['maxtotalimpacts'] = "1",
}, 

['ability_03'] = {
	['name'] = "Ability_Minerva3",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 2,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "passive",
}, 

['ability_04'] = {
	['name'] = "Ability_Minerva4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "600",
	['castactiontime'] = "300",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "enemy_units",
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
	['manacost'] = { [1] = 80,[2] = 95,[3] = 110, },
	['cooldowntime'] = "20000",
	['novoiceresponse'] = "true",
	['range'] = "200",
	['showareacast'] = "true",
	['hoverareacastrange'] = "200",
	['radius'] = "600",
	['targetselection'] = "closest",
	['targetscheme'] = "visible_enemy_heroes",
	['maxtotalimpacts'] = "1",
}, 
['moxie'] =  { 
['ability_01'] = {
	['name'] = "Ability_Moxie1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "500",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 65,[2] = 70,[3] = 75,[4] = 80, },
	['cooldowntime'] = "2500",
	['range'] = "625",
	['showareacast'] = "true",
	['hoverareacastrange'] = "625",
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
	['radius'] = "650",
	['targetselection'] = "closest",
	['targetscheme'] = "visible_enemy_heroes",
	['maxtotalimpacts'] = "1",
}, 

['ability_02'] = {
	['name'] = "Ability_Moxie2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2" ,
	['casttime'] = "400",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['manacost'] = "90",
	['cooldowntime'] = "7000",
	['range'] = "1000",
	['forcerange'] = "1000",
	['allowoutofboundscast'] = "true",
	['allowoutofrangecast'] = "true",
	['showlinecast'] = "true",
	['linecastwidth'] = "150",
	['linecastrange'] = "1150",
	['hoverareacastrange'] = "1150",
}, 

['ability_03'] = {
	['name'] = "Ability_Moxie3",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 2,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "passive",
	['powerratiomultiplier'] = { [1] = 0.03,[2] = 0.07,[3] = 0.11,[4] = 0.15, },
}, 

['ability_04'] = {
	['name'] = "Ability_Moxie4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "200",
	['castactiontime'] = "200",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_position",
	['targetradius'] = "325",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 115,[2] = 125,[3] = 135, },
	['cooldowntime'] = "90000",
	['hoverareacastrange'] = "1200",
	['range'] = "1200",
	['showareacast'] = "true",
}, 
['nikolai'] =  { 
['ability_01'] = {
	['name'] = "Ability_Nikolai1",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['anim'] = "ability_1",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['inheritmovement'] = "true",
	['queue'] = "front",
	['cooldowntime'] = { [1] = 17000,[2] = 14000,[3] = 12000,[4] = 10000, },
	['manacost'] = "80",
	['alwaysshowtimer'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Nikolai2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2" ,
	['casttime'] = "400",
	['castactiontime'] = "400",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['manacost'] = "100",
	['cooldowntime'] = "10000",
	['range'] = "950",
	['forcerange'] = "950",
	['allowoutofboundscast'] = "true",
	['allowoutofrangecast'] = "true",
	['showconecast'] = "true",
	['conecastwidth'] = "650",
	['conecastrange'] = "1200",
	['hoverareacastrange'] = "1050",
}, 

['ability_03'] = {
	['name'] = "Ability_Nikolai3",
	['icon'] = "icon.tga",
	['anim'] = "ability_3",
	['casttime'] = "350",
	['castactiontime'] = "350",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['manacost'] = "75",
	['queue'] = "front",
	['inheritmovement'] = "true",
	['range'] = "600",
	['cooldowntime'] = "13000",
	['hoverareacastrange'] = "600",
	['alwaysshowtimer'] = "true",
	['radius'] = "600",
	['targetselection'] = "all",
	['targetscheme'] = "visible_enemy_units",
}, 

['ability_04'] = {
	['name'] = "Ability_Nikolai4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "400",
	['castactiontime'] = "400",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_heroes",
	['queue'] = "dropmovement",
	['manacost'] = { [1] = 100,[2] = 110,[3] = 120, },
	['cooldowntime'] = { [1] = 60000,[2] = 50000,[3] = 40000, },
	['range'] = "525",
	['forcerange'] = "525",
	['allowoutofrangecast'] = "true",
	['showlinecast'] = "true",
	['linecastwidth'] = "130",
	['linecastrange'] = "590",
	['hoverareacastrange'] = "590",
	['showareacast'] = "false",
	['alwaysshowtimer'] = "true",
}, 
['ray'] =  { 
['ability_01'] = {
	['name'] = "Ability_Ray1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['targetradius'] = "350",
	['manacost'] = { [1] = 75,[2] = 80,[3] = 85,[4] = 90, },
	['cooldowntime'] = "4000",
	['maxcharges'] = "3",
	['range'] = "500",
	['showareacast'] = "true",
	['hoverareacastrange'] = "500",
}, 

['ability_02'] = {
	['name'] = "Ability_Ray2",
	['icon'] = "icon.tga",
	['casttime'] = "300",
	['castactiontime'] = "300",
	['anim'] = "ability_2",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 70,[2] = 80,[3] = 90,[4] = 100, },
	['cooldowntime'] = "14000",
	['range'] = "550",
	['novoiceresponse'] = "true",
	['targetradius'] = "300",
	['showareacast'] = "true",
	['hoverareacastrange'] = "580",
}, 

['ability_03'] = {
	['name'] = "Ability_Ray3",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "passive",
	['cooldowntime'] = { [1] = 10000,[2] = 8000,[3] = 6000,[4] = 4000, },
}, 

['ability_04'] = {
	['name'] = "Ability_Ray4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4b" ,
	['casttime'] = "600",
	['castactiontime'] = "600",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['manacost'] = "110",
	['cooldowntime'] = "90000",
	['range'] = "1800",
	['forcerange'] = "1800" ,
	['allowoutofboundscast'] = "true",
	['allowoutofrangecast'] = "true",
	['showlinecast'] = "true",
	['linecastrange'] = "1880",
	['linecastwidth'] = "120",
}, 
['rook'] =  { 
['ability_01'] = {
	['name'] = "Ability_Rook1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "100",
	['castactiontime'] = "100",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['responsetype'] = "Ability",
	['targetoffset'] = "0 0 0",
	['queue'] = "front",
	['manacost'] = "100",
	['cooldowntime'] = { [1] = 25000,[2] = 20000,[3] = 16000,[4] = 13000, },
	['range'] = "800",
	['forcerange'] = "800",
	['allowoutofrangecast'] = "true",
	['allowoutofboundscast'] = "true",
	['showlinecast'] = "true",
	['linecastrange'] = "800",
	['linecastmaxrange'] = "830",
	['linecastwidth'] = "130",
	['showareacast'] = "true",
	['alwaysshowtimer'] = "true",
	['ignorecooldown'] = "true",
	['anim'] = "",
	['icon'] = "icon_b.tga",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['manacost'] = "0",
	['actiontype'] = "no_target",
	['cooldowntime'] = "0",
	['activatescheme'] = "movement",
	['inheritmovement'] = "true",
	['noninterrupting'] = "true",
	['queue'] = "dropmovement",
	['ignorecooldown'] = "true",
	['anim'] = "",
	['icon'] = "icon_b.tga",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['manacost'] = "0",
	['actiontype'] = "no_target",
	['cooldowntime'] = "0",
	['activatescheme'] = "movement",
	['inheritmovement'] = "true",
	['noninterrupting'] = "true",
	['responsetype'] = "NoResponse",
}, 

['ability_02'] = {
	['name'] = "Ability_Rook2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2_down",
	['casttime'] = "500",
	['castactiontime'] = "0",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['ischanneling'] = "true",
	['channeltime'] = "1500",
	['manacost'] = "75",
	['cooldowntime'] = { [1] = 22000,[2] = 18000,[3] = 15000,[4] = 12000, },
	['hoverareacastrange'] = "625",
}, 

['ability_03'] = {
	['name'] = "Ability_Rook3",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "passive",
	['alwaysshowtimer'] = "true",
}, 

['ability_04'] = {
	['name'] = "Ability_Rook4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4_start",
	['casttime'] = "550",
	['castactiontime'] = "550",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_position",
	['targetradius'] = "100",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 110,[2] = 125,[3] = 140, },
	['cooldowntime'] = "90000",
	['range'] = "20000",
	['forcerange'] = "20000",
	['allowoutofboundscast'] = "true",
	['allowoutofrangecast'] = "true",
	['showlinecast'] = "true",
	['dontshowhovercast'] = "true",
	['linecastrange'] = "20000",
	['linecastwidth'] = "150",
}, 
['shank'] =  { 
['ability_01'] = {
	['name'] = "Ability_Shank1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "250",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "self_position",
	['targetscheme'] = "enemy_units",
	['queue'] = "front",
	['allowoutofrangecast'] = "true",
	['targetradius'] = "400",
	['manacost'] = { [1] = 95,[2] = 100,[3] = 105,[4] = 110, },
	['cooldowntime'] = "10000" ,
	['radius'] = "400",
	['targetselection'] = "all",
	['targetscheme'] = "enemy_units",
}, 

['ability_02'] = {
	['name'] = "Ability_Shank2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "200",
	['castactiontime'] = "200",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['queue'] = "front",
	['allowoutofrangecast'] = "true",
	['manacost'] = "50",
	['cooldowntime'] = { [1] = 23000,[2] = 16000,[3] = 12000,[4] = 9000, },
	['range'] = "1100",
	['showlinecast'] = "true",
	['linecastrange'] = "1150",
	['linecastwidth'] = "150",
	['showareacast'] = "true",
}, 

['ability_03'] = {
	['name'] = "Ability_Shank3",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "passive",
	['alwaysshowtimer'] = "true",
	['maxcharges'] = "3",
}, 

['ability_04'] = {
	['name'] = "Ability_Shank4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "300",
	['castactiontime'] = "300",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['novoiceresponse'] = "true",
	['allowoutofrangecast'] = "true",
	['manacost'] = "95",
	['cooldowntime'] = { [1] = 35000,[2] = 30000,[3] = 25000, },
	['range'] = "900",
	['forcerange'] = "900",
	['allowoutofboundscast'] = "true",
	['showlinecast'] = "true",
	['linecastrange'] = "1000",
	['linecastwidth'] = "100",
}, 
['trixie'] =  { 
['ability_01'] = {
	['name'] = "Ability_Trixie1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "400",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetradius'] = "260",
	['targetscheme'] = "enemy_units",
	['manacost'] = "100",
	['cooldowntime'] = "9000",
	['range'] = "625",
	['nohidecursor'] = "false",
	['showareacast'] = "true",
	['allowoutofrangecast'] = "true",
	['hoverareacastrange'] = "625",
}, 

['ability_02'] = {
	['name'] = "Ability_Trixie2",
	['icon'] = "icon.tga",
	['anim'] = "test",
	['casttime'] = "100",
	['castactiontime'] = "100",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "target_position",
	['activatescheme'] = "movement",
	['manacost'] = "70",
	['range'] = "500",
	['forcerange'] = "500",
	['cooldowntime'] = { [1] = 22000,[2] = 18000,[3] = 15000,[4] = 12000, },
	['noturntotarget'] = "true",
	['novoiceresponse'] = "true",
	['showlinecast'] = "true",
	['linecastrange'] = "500",
	['linecastwidth'] = "50",
	['queue'] = "dropmovement",
	['showareacast'] = "false",
	['allowoutofrangecast'] = "true",
	['usepathforrange'] = "true",
	['alwaysshowtimer'] = "true",
}, 

['ability_03'] = {
	['name'] = "Ability_Trixie3",
	['icon'] = "icon.tga",
	['anim'] = "ability_3",
	['casttime'] = "300",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "target_position",
	['activatescheme'] = "movement",
	['manacost'] = "100",
	['range'] = "1000",
	['forcerange'] = "900",
	['cooldowntime'] = "14000",
	['novoiceresponse'] = "true",
	['queue'] = "front",
	['showlinecast'] = "true",
	['linecastrange'] = "1000",
	['linecastwidth'] = "100",
	['showareacast'] = "false",
	['allowoutofrangecast'] = "true",
	['alwaysshowtimer'] = "true",
}, 

['ability_04'] = {
	['name'] = "Ability_Trixie4",
	['icon'] = "icon.tga",
	['anim'] = "ability_3",
	['casttime'] = "200",
	['castactiontime'] = "200",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_position",
	['targetradius'] = "350",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 100,[2] = 110,[3] = 120, },
	['cooldowntime'] = "120000",
	['range'] = "700",
	['showareacast'] = "true",
}, 
['vermillion'] =  { 
['ability_01'] = {
	['name'] = "Ability_Vermillion1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "500",
	['castactiontime'] = "300",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetradius'] = "300",
	['targetscheme'] = "enemy_units_and_Towers",
	['manacost'] = { [1] = 90,[2] = 105,[3] = 120,[4] = 135, },
	['cooldowntime'] = "8000",
	['range'] = "650",
	['showareacast'] = "true",
	['hoverhoverareacastrange'] = "650",
	['novoiceresponse'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Vermillion2",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "passive",
	['maxcharges'] = { [1] = 6,[2] = 5,[3] = 4,[4] = 3, },
	['alwaysshowtimer'] = "true",
}, 

['ability_03'] = {
	['name'] = "Ability_Vermillion3",
	['icon'] = "icon.tga",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['attackrange'] = { [1] = 45,[2] = 80,[3] = 115,[4] = 150, },
	['basedamage'] = { [1] = 2,[2] = 4,[3] = 6,[4] = 8, },
	['actiontype'] = "passive",
}, 

['ability_04'] = {
	['name'] = "Ability_Vermillion4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "300",
	['castactiontime'] = "150",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_position",
	['targetradius'] = "200",
	['targetscheme'] = "enemy_units",
	['range'] = "600",
	['manacost'] = { [1] = 130,[2] = 150,[3] = 170, },
	['cooldowntime'] = "90000",
	['queue'] = "dropmovement",
	['showareacast'] = "true",
}, 
['vex'] =  { 
['ability_01'] = {
	['name'] = "Ability_Vex1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1" ,
	['casttime'] = "400",
	['castactiontime'] = "200",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 70,[2] = 75,[3] = 80,[4] = 85, },
	['cooldowntime'] = "6000",
	['range'] = "1200",
	['forcerange'] = "1200",
	['allowoutofrangecast'] = "true",
	['showlinecast'] = "true",
	['linecastrange'] = "1200",
	['linecastwidth'] = "120",
}, 

['ability_02'] = {
	['name'] = "Ability_Vex2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "self_position",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 85,[2] = 95,[3] = 105,[4] = 115, },
	['cooldowntime'] = "11000",
	['hoverareacastrange'] = "600",
	['queue'] = "front",
	['inheritmovement'] = "true",
	['alwaysshowtimer'] = "true",
}, 

['ability_03'] = {
	['name'] = "Ability_Vex3",
	['icon'] = "icon.tga",
	['anim'] = "ability_3",
	['casttime'] = "100",
	['castactiontime'] = "0",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "ally_units",
	['manacost'] = "75",
	['cooldowntime'] = { [1] = 24000,[2] = 21000,[3] = 18000,[4] = 15000, },
	['showareacast'] = "true",
	['hoverareacastrange'] = "580",
	['range'] = "550",
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
	['radius'] = "750",
	['targetselection'] = "closest",
	['targetscheme'] = "ally_heroes",
	['maxtotalimpacts'] = "1",
}, 

['ability_04'] = {
	['name'] = "Ability_Vex4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "0",
	['castactiontime'] = "0",
	['channeltime'] = "2000",
	['ischanneling'] = "true",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_position",
	['targetscheme'] = "Vex_Teleport",
	['manacost'] = { [1] = 110,[2] = 120,[3] = 130, },
	['cooldowntime'] = { [1] = 125000,[2] = 110000,[3] = 95000, },
	['targetradius'] = "400",
	['range'] = "999999",
	['hoverareacastrange'] = "1",
	['radius'] = "400",
	['targetselection'] = "all",
	['targetscheme'] = "enemy_units",
}, 
['zaku'] =  { 
['ability_01'] = {
	['name'] = "Ability_Zaku1",
	['icon'] = "icon.tga",
	['anim'] = "ability_1",
	['casttime'] = "100",
	['castactiontime'] = "100",
	['channeltime'] = "3000",
	['ischanneling'] = "true",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 70,[2] = 80,[3] = 90,[4] = 100, },
	['cooldowntime'] = "8000",
	['showlinecast'] = "true",
	['linecastwidth'] = "150",
	['linecastrange'] = "865",
	['allowoutofrangecast'] = "true",
	['range'] = "865",
	['forcerange'] = "865",
	['hoverareacastrange'] = "865",
	['alwaysshowtimer'] = "true",
}, 

['ability_02'] = {
	['name'] = "Ability_Zaku2",
	['icon'] = "icon.tga",
	['anim'] = "ability_2",
	['casttime'] = "250",
	['castactiontime'] = "250",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_position",
	['targetradius'] = "175",
	['targetscheme'] = "enemy_units",
	['manacost'] = { [1] = 70,[2] = 80,[3] = 90,[4] = 100, },
	['cooldowntime'] = "12000",
	['range'] = "550",
	['showareacast'] = "true",
	['maxcharges'] = "2",
}, 

['ability_03'] = {
	['name'] = "Ability_Zaku3",
	['icon'] = "icon.tga",
	['anim'] = "ability_3",
	['casttime'] = "250",
	['castactiontime'] = "250",
	['maxlevel'] = "4",
	['requiredlevel'] = { [1] = 1,[2] = 3,[3] = 5,[4] = 7, },
	['actiontype'] = "target_self",
	['targetradius'] = "0",
	['manacost'] = "90",
	['cooldowntime'] = "12000",
	['range'] = "550",
	['queue'] = "front",
	['noentercombat'] = "true",
	['showareacast'] = "true" ,
	['maxcharges'] = "3",
}, 

['ability_04'] = {
	['name'] = "Ability_Zaku4",
	['icon'] = "icon.tga",
	['anim'] = "ability_4",
	['casttime'] = "300",
	['castactiontime'] = "300",
	['maxlevel'] = "3",
	['requiredlevel'] = { [1] = 6,[2] = 11,[3] = 15, },
	['actiontype'] = "target_entity",
	['targetscheme'] = "ally_heroes",
	['showareacast'] = "true",
	['manacost'] = { [1] = 110,[2] = 125,[3] = 140, },
	['cooldowntime'] = { [1] = 120000,[2] = 90000,[3] = 60000, },
	['range'] = "800",
	['doubleactivate'] = "true",
	['doubleactivatenoninterrupting'] = "true",
}, 

} 
